apiVersion: apps/v1
kind: Deployment
metadata:
  name: final-project-deployment
  labels:
    app: final-project-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: final-project-service
  template:
    metadata:
      labels:
        app: final-project-service
    spec:
      containers:
      - name: web
        image: 721167874930.dkr.ecr.us-east-1.amazonaws.com/final-project:latest
        ports:
          - name: web
            containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service loadbalance
spec:
  selector:
    app: final-project-service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80